# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports: 
      - 5432:5432
    volumes:
      - nodejs-db:/var/lib/postgresql/data

  nodejsapp:
    build:
      context: .
    environment:
      - DATABASE_URL= postgresql://postgres:123@$localhost:5432/testdb?schema=public
    command:
      - npx prisma migrate deploy
    depends_on:
      - postgres
    ports:
      - '5000:5000'
        
volumes:
  nodejs-db: