name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull nodejsapp

      - name: Deploy Docker Compose application
        run: docker-compose up -d
